// <auto-generated />
using System;
using CuaHangTienLoiTDA.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CuaHangTienLoiTDA.Migrations
{
    [DbContext(typeof(CuaHangTienLoiTDAContext))]
    partial class CuaHangTienLoiTDAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CuaHangTienLoiTDA.Models.Admin", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"));

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaNV")
                        .HasName("PK__Admin__2725D70AB590B308");

                    b.HasIndex(new[] { "Email" }, "UQ__Admin__A9D105341AE74868")
                        .IsUnique();

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("CuaHangTienLoiTDA.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaCTDH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTDH"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MaDH")
                        .HasColumnType("int");

                    b.Property<int>("MaSP")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaCTDH")
                        .HasName("PK__ChiTietD__1E4E40F060D41D5B");

                    b.HasIndex("MaDH");

                    b.HasIndex("MaSP");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("CuaHangTienLoiTDA.Models.DanhMucSanPham", b =>
                {
                    b.Property<int>("MaDM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDM"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDM")
                        .HasName("PK__DanhMucS__2725866E6B07BF62");

                    b.ToTable("DanhMucSanPham", (string)null);
                });

            modelBuilder.Entity("CuaHangTienLoiTDA.Models.DonHang", b =>
                {
                    b.Property<int>("MaDH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDH"));

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chờ duyệt");

                    b.HasKey("MaDH")
                        .HasName("PK__DonHang__272586611D4C6561");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaNV");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("CuaHangTienLoiTDA.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<string>("ChucVu")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("KhachHang");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaKH")
                        .HasName("PK__KhachHan__2725CF1EF79EC6BD");

                    b.HasIndex(new[] { "Email" }, "UQ__KhachHan__A9D1053459C60B54")
                        .IsUnique();

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("CuaHangTienLoiTDA.Models.SanPham", b =>
                {
                    b.Property<int>("MaSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSP"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaDM")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaSP")
                        .HasName("PK__SanPham__2725081CEBF9D79C");

                    b.HasIndex("MaDM");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("CuaHangTienLoiTDA.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("CuaHangTienLoiTDA.Models.DonHang", "MaDHNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDH")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDon__MaDH__5FB337D6");

                    b.HasOne("CuaHangTienLoiTDA.Models.SanPham", "MaSPNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaSP")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDon__MaSP__60A75C0F");

                    b.Navigation("MaDHNavigation");

                    b.Navigation("MaSPNavigation");
                });

            modelBuilder.Entity("CuaHangTienLoiTDA.Models.DonHang", b =>
                {
                    b.HasOne("CuaHangTienLoiTDA.Models.KhachHang", "MaKHNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKH")
                        .IsRequired()
                        .HasConstraintName("FK__DonHang__MaKH__5BE2A6F2");

                    b.HasOne("CuaHangTienLoiTDA.Models.Admin", "MaNVNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaNV")
                        .HasConstraintName("FK__DonHang__MaNV__5CD6CB2B");

                    b.Navigation("MaKHNavigation");

                    b.Navigation("MaNVNavigation");
                });

            modelBuilder.Entity("CuaHangTienLoiTDA.Models.SanPham", b =>
                {
                    b.HasOne("CuaHangTienLoiTDA.Models.DanhMucSanPham", "MaDMNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDM")
                        .IsRequired()
                        .HasConstraintName("FK__SanPham__MaDM__571DF1D5");

                    b.Navigation("MaDMNavigation");
                });

            modelBuilder.Entity("CuaHangTienLoiTDA.Models.Admin", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("CuaHangTienLoiTDA.Models.DanhMucSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("CuaHangTienLoiTDA.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("CuaHangTienLoiTDA.Models.KhachHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("CuaHangTienLoiTDA.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
